USE [TestFramework]
GO

/****** Object:  Table [dbo].[D_TEST_DEF]    Script Date: 12/4/2015 10:35:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[D_TEST_DEF](
	[TEST_DEF_ID] [int] IDENTITY(1,1) NOT NULL,
	[TEST_DEF_CD] [varchar](20) NULL,
	[TEST_DEF_DESC] [varchar](500) NOT NULL,
	[TEST_QUERY] [varchar](max) NULL,
	[EXPECTED_RESULT] varchar(500) NULL,
	[RET_COLUMN_CNT] [int] NULL,
	[VERSION_NUM] [numeric](10, 2) NULL,
	[CURRENT_VERSION_FLG] [char](1) NULL,
	[ACTIVE_FLG] [char](1) NULL,
	[CREATE_USER] [varchar](100) NULL,
	[CREATE_DT] [datetime] NULL,
	[UPDATE_USER] [varchar](100) NULL,
	[UPDATE_DT] [datetime] NULL,
	[EXPECTED_RESULT_QUERY] [varchar](max) NULL,
 CONSTRAINT [PK_D_TEST_DEF] PRIMARY KEY CLUSTERED 
(
	[TEST_DEF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


