USE [TestFramework]
GO

/****** Object:  Table [dbo].[F_TEST_RESULTS]    Script Date: 12/4/2015 10:45:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

-- drop table [dbo].[F_TEST_RESULTS]

CREATE TABLE [dbo].[F_TEST_RESULTS](
	[TEST_RESULT_ID] [bigint] IDENTITY(1,1) NOT NULL,
	[TEST_DEF_ID] [int] NOT NULL,
	[TEST_DATE] [date] NOT NULL,
	[TEST_VALUE] VARCHAR(500) NULL,
	[CURRENT_FLG] [char](1) NOT NULL,
	[CREATE_USER] [varchar](100) NOT NULL,
	[CREATE_DT] [datetime] NOT NULL,
	[TEST_DATA_FLG] [char](1) NOT NULL,
	[RUNTIME_SECS] [bigint] NULL,
	[EXPECTED_RESULT] VARCHAR(500) NULL,
	[GROUP_BY] [varchar](max) NULL,
 CONSTRAINT [PK_F_CALC_CUSTOM_METRICS] PRIMARY KEY CLUSTERED 
(
	[TEST_RESULT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


